### PR TITLE
Add ObjectDriver

### PR DESCRIPTION
**Pull request by nclavaud**
fixes https://github.com/spatie/phpunit-snapshot-assertions/issues/46

Add an `ObjectDriver` that relies on [Symfony Serializer](https://symfony.com/doc/current/components/serializer.html) and will snapshot public properties and the return of public getters into readable JSON.

Internally, it uses the `ObjectNormalizer` that does a pretty decent job at normalizing any object, and the `DateTimeNormalizer` so the output for `DateTime` objects is not too verbose.

This was motivated by offering a more convenient alternative to the current `VarDriver`.

My main concert about the `VarDriver` is that it does not only capture public properties, but also private and protected properties, whereas in my opinion, the original idea behind snapshot testing is to capture only the public surface of the system under test.

### CODE REVIEW

**Comment by sebastiandedeyne** [comment]
> My main concert about the VarDriver is that it does not only capture public properties, but also private and protected properties, whereas in my opinion, the original idea behind snapshot testing is to capture only the public surface of the system under test.

I never really considered this and I agree.

Do you think it would make more sense to have this as the default behaviour, and drop `VarDriver` support? (in a new major version of course)

**Comment by nclavaud** [comment]
> Do you think it would make more sense to have this as the default behaviour, and drop `VarDriver` support? (in a new major version of course)

Yes, definitely :+1: 

I was planning to do what you suggests in another PR, but I can push more commits here if needed.

**Comment by sebastiandedeyne** [comment]
Go for it here!

I'll tag it in a new major version then.

**Comment by nclavaud** [comment]
I have been adding more coverage to make sure the old `VarDriver` could be dropped in favor of the new driver.

Still pending on https://github.com/symfony/symfony/pull/35596 to support simple \stdClass objects.

Also, this new driver can handle not only objects, but also scalars, so maybe a name like `SymfonySerializerDriver` would fit better.

**Comment by sebastiandedeyne** [comment]
Thanks! Gonna finish and tag this on `master` :)

**Pull request merged**
