### PR TITLE
Upgrade PHPUnit from 7 to 8 (php 7.2 required)

### PR DESCRIPTION
**Pull request by romainnorberg**
The proposal is the support of PhpUnit 8 and php 7.2 _(or newer)_ requirement. [Active support for PHP 7.1 ended on December 1, 2018](https://secure.php.net/supported-versions.php)

### Todo
- [x] update readme

### CODE REVIEW

**Comment by DanielBadura** [comment]
In the travis-ci.yml php7.1 has to be removed.

On the other hand i thought on letting PHPUnit 7 and 8 valid for now `"phpunit/phpunit": "^7.0|^8.0"`. Otherwise this package needs to dump again the major version with this change.

**Comment by sebastiandedeyne** [comment]
No need to tag a new majro version when upgrading underlying version constraints, Composer already takes care of resolving the correct package version.

Looks good to me, gonna push forward. Thanks!

**Comment by romainnorberg** [comment]
Thanks @sebastiandedeyne 🚀 

According to @DanielBadura, we should remove php7.1 from travis.ci ?

**Comment by sebastiandedeyne** [comment]
Already done :)

https://github.com/spatie/phpunit-snapshot-assertions/commit/da0d1449eb2c982cf897e94ea72f1b38a2bff05c

**Pull request merged**
