### PR TITLE
correct json driver to not force all objects to arrays (in particular…

### LINKED ISSUE #73: Empty json objects encoded as arrays
Hi,

When an empty object is used it is been serialised and snapshotted as an array, for example this will fail once the snapshot is created:

```
    public function testJsonSnapshot()
    {
        $json = json_encode((object) [
            'data' => [
                'objectData' => (object)[]
            ]
        ]);

        // dump($json);
        // {"data":{"objectData":{}}}

        $this->assertMatchesJsonSnapshot($json);
        // snapshot contents
        /*
        {
            "data": {
                "objectData": []
            }
        }
        */

    }
```
basically `[]` in the snapshot vs `{}` in the $json variable

Paul

### PR DESCRIPTION
**Pull request by mintbridge**
… when empty), fixes #73

### CODE REVIEW

**Comment by mintbridge** [comment]
This is a breaking change as all previous snapshots that relied on the empty objects being cast will now fail

**Comment by mintbridge** [comment]
@freekmurze any thoughts?

**Comment by mintbridge** [comment]
This is working for us, but not sure how to get it into the master branch?

**Comment by ThHareau** [comment]
This PR can solve the issue #77 as well

**Comment by sebastiandedeyne** [comment]
Looks good, I'm gonna tag a new major version for this 👍

**Pull request merged**
